### PR TITLE
Fix issue #86 and issue #103 combined 

### PR DESCRIPTION
**Pull request by Wormfriend**
This is a combined proposed fix for the issues #86 and #103. for #86 I implemented a conditional within unpack_nested checking for many=True and if wrapping fr.Nested into a fr.List as in unpack_nested_self. For #103 I added type-checking for ma.utils._Missing. Thank you for your work!

### CODE REVIEW

**Comment by Wormfriend** [comment]
I just realised it crashes at some point with flask restx . I'll add additional testing. Sorry. #86 should be fine though.

**Comment by Wormfriend** [comment]
Ok, my bad - it was an error in my test-application. If you like I can also upload some short test-app.

**Comment by osovv** [comment]
Can't wait for it to be merged. It sucks to make it by hands for every new environment.

**Comment by dabi0ne** [comment]
Thank @Wormfriend for the fixes. Had the same issue after an upgrade and the proposed fixes worked well, waiting for the merge.
@apryor6 Thank you for this great project !

**Comment by apryor6** [comment]
Apologies for the delay and thanks! This is now available on 0.18.2 on PyPi.

**Pull request merged**
