### PR TITLE
Issue #36. Added 'required', 'default' and 'description' fields to result Swagger docs

### PR DESCRIPTION
**Pull request by AndreyKis**
Resolves Issue #36 
Was thinking about ways to get rid of same function call for every type.

Thought of functional programming approach, but decided to leave it like that for now. Mainly, because of last 4 types in the dictionary (ma.List, ma.Nested, Schema and SchemaMeta). They messed up all ideas I was thinking about. Like using mapping function over dictionary with types map.

Any ideas on how code quality can be improved in this context?

### CODE REVIEW

**Comment by apryor6** [comment]
I made some candidate changes along what you were suggesting [here](https://github.com/AndreyKis/flask_accepts/pull/1)

**Comment by AndreyKis** [comment]
I think, I got lost in versions in changelog a little bit as there were a couple of changes merged while this PR was opened.

Should it still be 0.13 or should I change it to 0.15? It seems like other changes were merged into master with 0.14, though 0.13 wasn't there yet.

**Comment by apryor6** [comment]
Just pull from upstream master to get the latest, and then I'll deal with incrementing the version:

```
git pull upstream master
```

There were a couple of other issues I fixed yesterday, hence the updated code

**Comment by AndreyKis** [comment]
Yeah, I've pulled changes this morning so there would be no conflicts.

Just saw some changes in changelog while resolving conflicts and mentioned that in previous comment.

Except of changelog, MR should be good to go, I think.

**Comment by AndreyKis** [comment]
Hi. Could you tell me, please, if you are planning to merge this PR?

I am currently working on marshmallow + flask_accepts a lot and have a lot of other things I would like to add. Like envelope support, custom_fields support (currently app breaks if I create my custom field, extending existing one) and some other features.

However I would like to install latest version of flask_accepts with all changes included before doing so. So I would be grateful if you could merge it this PR if you think it is ready to go.

**Comment by apryor6** [comment]
Yes looks good to me. For some reason I thought this was still a draft PR. My mistake!

**Comment by AndreyKis** [comment]
Great! Thank you.

**Comment by apryor6** [comment]
Closes #36 and #33

**Comment by AndreyKis** [comment]
Hi again. Sorry for bothering you, but have you changed version in changelog as discussed?

As far as I understood, it is still 0.14 in PyPI, while changes from this PR are marked with version 0.13. However, 0.14 was uploaded to PyPI before 0.13 got merged into master. This causes PyPI still having 0.14 version without changes from this PR.

**Comment by apryor6** [comment]
Good catch, sorry about that. Now in 0.14.1

https://pypi.org/project/flask-accepts/0.14.1/
https://github.com/apryor6/flask_accepts/releases/tag/v0.14.1

**Pull request merged**
