### PR TITLE
Resolve marshmallow deprecation warning and support marshmallow 4.0

### PR DESCRIPTION
**Pull request by kreathon**
Proposal for https://github.com/apryor6/flask_accepts/issues/116.

### CODE REVIEW

**Comment by kreathon** [comment]
I am not sure how to handle the test coverage decrease. 

Proper testing could involve running multiple _tox_ environments and merging the coverage reports.

**Comment by kreathon** [comment]
Alternatively, marshmallow could be pinned to <4.0 for now.

**Comment by circulon** [comment]
@kreathon 
did you get this resolved? 
I would like to use flask_accepts with marshmallow 4 in my project

The issue looks to be here:
```python
if marshmallow_version >= (3, 13, 0):
    _ma_key_for_fr_example_key = "dump_default"
    _ma_key_for_fr_default_key = "load_default"
else:
    _ma_key_for_fr_example_key = "default"
    _ma_key_for_fr_default_key = "missing"
```
where the lines after the `else` look to be ignored?
maybe something like this would work for the code coverage instead?
```python

_ma_key_for_fr_example_key = "dump_default"
_ma_key_for_fr_default_key = "load_default"
if marshmallow_version < (3, 13, 0):
    _ma_key_for_fr_example_key = "default"
    _ma_key_for_fr_default_key = "missing"
```
I would be interested to know if this works?

@apryor6 can you provide any additional feedback?
Additionally how do we run the code coverage tests locally please?

**Comment by kreathon** [comment]
You can check the `.circleci/config.yml` to see how to run the code coverage tests locally.

But my fear is that this project is dead.

**Comment by circulon** [comment]
> But my fear is that this project is dead (and it is not about coverage)

Bugger ;(  

@kreathon  are you working with or know of any other projects that are active and provide similar functionality?

Cheers

**Comment by kreathon** [comment]
@circulon I don't know. Personally, I am now sticking to plain Marshmallow.

**Pull request merged**
