### PR TITLE
Add ma.Method to fields_map

### PR DESCRIPTION
**Pull request by ribeirojose**
I'd love to add tests here, but in a quick glance through the tests I was not really sure on the best way to do it. Any suggestions?

### CODE REVIEW

**Comment by apryor6** [comment]
For a change like this, the simplest test would be against `map_type` to assert that passing in `ma.Method` as a field produces the expected corresponding output.

**Comment by ribeirojose** [comment]
Updated with a simple test!

**Comment by ribeirojose** [comment]
@apryor6 just checking and making sure to overcommunicate. Do we need to add anything else here?

**Comment by apryor6** [comment]
LGTM!

**Comment by apryor6** [comment]
Available on pypi now as 0.17.2

**Pull request merged**
